import requests
import time

# The official live global URL generated by the tunnel bridge
GLOBAL_GATEWAY_URL = "https://open-chicken-listen.loca.lt"

print("--- [Global Enterprise Environment]: Initializing Cross-Border Network Handshake ---")
time.sleep(1)

# Payload dataset containing the transaction matrix
payload = {
    "sender": "Agent_Sender",
    "receiver": "Agent_Omega",
    "amount": 35.0
}

print(f"\n[Global Dispatch]: Shipping 35.0 USD asset packet via secure gateway link...")

try:
    # Querying the secure global server endpoint over the live internet
    response = requests.post(f"{GLOBAL_GATEWAY_URL}/api/v1/transfer", json=payload, timeout=10)
    
    if response.status_code == 200:
        print("✅ [Global Network Success]: Transaction successfully settled over the international highway!")
        print(f"Server Response: {response.json()}")
    else:
        print(f"❌ [Global Network Error]: Core rejected payload. Code: {response.status_code}")
        print(f"Server Response: {response.text}")
except Exception as e:
    print(f"❌ [Global Network Exception]: Connection timed out or routing failed. Error: {str(e)}")
